import ProjectDescription
import ProjectDescriptionHelpers

let essentialAppTarget = TargetReference.project(
    path: "EssentialApp",
    target: "EssentialApp"
)

let ciIOSScheme: Scheme = .scheme(
    name: "CI_iOS",
    buildAction: .buildAction(targets: [essentialAppTarget]),
    testAction: .testPlans(
        [.path("Testplans/CI_iOS.xctestplan")]
    ),
    runAction: .runAction(configuration: .essentialAppDebug, executable: essentialAppTarget),
    archiveAction: .archiveAction(configuration: .essentialAppRelease),
    analyzeAction: .analyzeAction(configuration: .essentialAppRelease)
)

let workspace = Workspace(
    name: "EssentialApp",
    projects: ["EssentialFeed", "EssentialApp"],
    schemes: [ciIOSScheme],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)

