name: "EssentialFeed Framework macOS Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-14
  
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app

      - name: Xcode version
        run: xcodebuild -version

      - name: Build and Test
        run: |
          xcodebuild clean build test \
          -project EssentialFeed.xcodeproj \
          -scheme EssentialFeed \
          -sdk macosx \
          -destination "platform=macOS" \
          -testPlan EssentialFeedCI \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES