name: CI-iOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Generate Project using tuist
        run: tuist generate

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      - name: Xcode version
        run: xcodebuild -version

      - name: Build and Test CI_iOS Scheme
        run: |
          set -o pipefail && xcodebuild clean build test \
          -workspace EssentialApp.xcworkspace \
          -scheme CI_iOS \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5" \
          -testPlan CI_iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES | xcbeautify --renderer github-actions

